<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 (Total recall)

#### Subsetting
_To 'select' an element_

#### Indexing
To select a specific element based on their relative position

#### Slicing
To select a portion of the elements in the list

#### Masking
To select a portion of the elements by 'hiding' elements that does not fulfil the condition stated

### Exercise 2 (Show me the 'odd' letters')

In [66]:
import numpy as np

In [6]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d_numbers = np_array_2d[0:,0]
np_array_int = np_array_2d_numbers.astype(int)
np_mask = np_array_int % 2 == 1
np_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [7]:
np_array_masked = np_array_2d[np_mask == True]
np_array_masked[0:, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

### Exercise 3

In [61]:
py_list = [[66, 50, 57, -1, -1], [92, -1, 88, -1, -1], [75, -1, -1, 76, -1], [-1, 51, 87, -1, -1], [71, -1, 67, -1, 69]]
np_array = np.array(py_list)
np_array

array([[66, 50, 57, -1, -1],
       [92, -1, 88, -1, -1],
       [75, -1, -1, 76, -1],
       [-1, 51, 87, -1, -1],
       [71, -1, 67, -1, 69]])

In [64]:
mask_1 = np_array == 50
np_array[mask_1] = 0
np_array

array([[66,  0, 57, -1, -1],
       [92, -1, 88, -1, -1],
       [75, -1, -1, 76, -1],
       [-1, 51, 87, -1, -1],
       [71, -1, 67, -1, 69]])

In [74]:
mask_2 = np_array < 50 & ~(np_array == 0)
np_array[mask_2] = -1
mask_3 = np_array > 50
np_array[mask_3] = 1
np_array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])